accton_as5712_54x: 'http://178.33.61.6/putstorage/DownloadFileHash/AA90EC2D3A5A4A5QQWE3332069EWQS/onie-installer-x86_64-accton_as6712_32x-r0'
accton_as6712_32x: 'http://178.33.61.6/putstorage/DownloadFileHash/AA90EC2D3A5A4A5QQWE3332069EWQS/onie-installer-x86_64-accton_as6712_32x-r0'

virtualbox:
    # CHANGE:
    #   'power_helper_user' specifies the user to use when SSHing to the host
    #                       that is running virtualbox
    #   'power_helper_host' specifies the IP address of host that is running
    #                       virtualbox. will be dynamically set if empty string
    power_helper_user: "{{ power_helper_user | default('cord') }}"
    power_helper_host: "{{ power_helper_host | default('') }}"

maas:
    admin_email: "{{ admin_email | default('admin@cord.lab') }}"
    user: "{{ maas_user | default('cord') }}"
    user_password: "{{ maas_password | default('cord') }}"
    user_email: "{{ maas_email | default('cord@cord.lab') }}"
    user_sshkey: "{{ lookup('file', 'files/cord_id_rsa.pub') }}"

    # CHANGE:
    #   'domain' specifies the domain name configured in to MAAS
    domain: "{{ domain | default('cord.lab') }}"

interfaces:
    # CHANGE:
    #   'external'   specifies the interface on which the head node is
    #                connected to the internet
    #   'management' specifies the interface on which the head node will
    #                service DHCP and PXE boot requests
    fabric: "{{ fabric_iface | default('fabric') }}"
    management: "{{ management_iface | default('mgmtbr') }}"
    external: "{{ external_iface | default('') }}"

networks:
    # CHANGE:
    #   'management' specifies the network that MAAS will allocate
    #                via DHCP over the 'management' interface specified
    #                above
    #   'bridge'     specifies the network that MAAS will allocate
    #                via DHCP to the VM created in support of XOS
    #                on the head node.
    #   'fabric'     specifies the network that will be assigned to
    #                the leaf - spine fabric
    management: "{{ management_network | default('10.6.0.0/24') }}"
    bridge: "{{ bridge_network | default('172.42.0.0/24') }}"
    fabric: "{{ fabric_network | default('10.6.1.0/24') }}"

    # CHANGE:
    #   'bridge' name of the bride to create that is used when connecting
    #            the VMs created in support of XOS
    bridge_name: "{{ bridge_name | default('mgmtbr') }}"

docker:
    registry: "{{ docker_registry | default('opencord') }}"
    image_version: "{{ docker_image_version | default('latest') }}"
