- name: Ensure Hostname Resolution
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: 127.0.0.1 docker-registry
    owner: root
    group: root
    mode: "0644"

- name: Directories are present
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - /data/registry-mirror/conf
  tags: [registry]

- name: Configuration is copied
  become: yes
  copy:
    src: mirror-config.yml
    dest: /data/registry-mirror/conf/config.yml
  tags: [registry]

- name: Ensure Directories
  become: yes
  file:
    path: /etc/maas
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Local Docker Registry
  become: yes
  template:
    src: templates/{{ item }}.j2
    dest: /etc/maas/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - registry-compose.yml
  tags: [registry]

- name: Ensure Local Registry Running
  become: yes
  command: docker-compose -f /etc/maas/{{ item }} up -d
  with_items:
    - registry-compose.yml
  changed_when: true
  tags: [registry]
