---
# install MaaS on head node

- name: run setup to gather facts
  hosts: all, localhost
  tasks:
    - name: run setup
      setup:

- name: Install MaaS and supporting files on head node
  hosts: head
  roles:
    - head-node
    - registry

