---
- name: User Local bin directory
  file:
    path=/home/{{ ansible_user }}/bin
    state=directory
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0755

- name: Copy Utility Commands
  copy:
    src=files/bin/{{ item }}
    dest=/home/{{ ansible_user }}/bin
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0755
  with_items:
    - minify
    - onos-cfg-get
    - onos-cfg-post
    - onos-cfg-delete
    - ping-test.sh

- name: Include Utility Commands in User Path
  lineinfile:
    dest=/home/{{ ansible_user }}/.bashrc
    line="PATH=$HOME/bin:$PATH"
    state=present
    insertafter=EOF

- name: Custom ONOS
  unarchive:
    src=files/onos-1.6.0.ubuntu.tar.gz
    dest=/home/{{ ansible_user }}
    owner={{ ansible_user }}
    group={{ ansible_user }}

- name: ONOS Fabric Configuration
  template:
    src=templates/fabric-network-config.json.j2
    dest=/home/{{ ansible_user }}/fabric-network.config.json
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0644
    
