pub_ssh_key: "{{ lookup('file', 'files/id_rsa.pub') }}"

compute_node:
    interfaces:
        fabric: "{{ fabric_iface | default('fabric') }}"
        management: "{{ management_iface | default('br-mgmt') }}"
        external: "{{ external_iface | default('') }}"
    addresses:
        fabric: "{{ fabric_ip | mandatory }}"
        management: "{{ management_ip | default('dhcp') }}"
        external: "{{ external_ip | default('manual') }}"
