pub_ssh_key: "{{ lookup('file', 'files/id_rsa.pub') }}"

compute_node:
    fabric_iface_match: "{{ fabric_iface_spec | default('i40e|mlx4_en') }}"
    interfaces:
        fabric: "{{ fabric_iface | default('fabric') }}"
        management: "{{ management_iface | default('mgmtbr') }}"
        external: "{{ external_iface | default('') }}"
    addresses:
        fabric: "{{ fabric_ip | mandatory }}"
        management: "{{ management_ip | default('dhcp') }}"
        external: "{{ external_ip | default('manual') }}"
    gateway:
        external: "{{ external_gw | default('') }}"
        management: "{{ management_gw | default('') }}"
