---
galaxy_info:
  author: Ciena Blueplanet
  description: Services required to bare metal boot CORD POD
  company: Ciena Blueplanet
  license: Apache 2.0
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  galaxy_tags:
    - cord
dependencies:
  - { role : compute-node }
