---
- name: Applications
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - build-essential 

- name: Set Default Password
  become: yes
  user:
    name={{ ansible_user }}
    password="$6$TjhJuOgh8xp.v$z/4GwFbn5koVmkD6Ex9wY7bgP7L3uP2ujZkZSs1HNdzQdz9YclbnZH9GvqMC/M1iwC0MceL05.13HoFz/bai0/"
  when: '"{{ ansible_user }}" == "ubuntu"'

- name: Authorize SSH Key
  become: yes
  authorized_key:
    key="{{ pub_ssh_key }}"
    user={{ ansible_user }}
    state=present

- name: Verify Private SSH Key
  become: yes
  stat:
    path=/home/{{ ansible_user }}/.ssh/id_rsa
  register: private_key

- name: Ensure SSH Key
  become: yes
  copy:
    src=files/{{ item }}
    dest=/home/{{ ansible_user }}/.ssh/{{ item }}
    owner={{ ansible_user }}
    group={{ ansible_user }}
    mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Ensure CORD SUDO
  become: yes
  copy:
    src=files/99-cord-sudoers
    dest=/etc/sudoers.d/99-cord-sudoers
    owner=root
    group=root
    mode=0600

- name: Verify i40e Driver
  command: modinfo --field=version i40e
  register: i40e_version
  changed_when: False
  failed_when: False
  tags:
    - interface_config

- name: Update i40e Driver
  include: tasks/i40e_driver.yml
  when: i40e_version.stdout != '1.4.25'
  tags:
    - interface_config

- name: Consistent Interface Naming
  become: yes
  script: files/rename_ifaces.sh {{ fabric_ip }}
  register: ifaces_changed
  changed_when: ifaces_changed.stdout != "false"
  tags:
    - interface_config

- name: Reboot Required
  become: yes
  command: /sbin/reboot
  when: ifaces_changed.stdout != "false"
  tags:
    - interface_config
