---
- name: Applications
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - build-essential 

- name: Set Default Password
  become: yes
  user:
    name=ubuntu
    password="$6$TjhJuOgh8xp.v$z/4GwFbn5koVmkD6Ex9wY7bgP7L3uP2ujZkZSs1HNdzQdz9YclbnZH9GvqMC/M1iwC0MceL05.13HoFz/bai0/"

- name: Verify i40e Driver
  command: modinfo --field=version i40e
  register: i40e_version
  changed_when: False

- name: Update i40e Driver
  include: tasks/i40e_driver.yml
  when: i40e_version.stdout != '1.4.25'

- name: Consistent Interface Naming
  become: yes
  script: files/rename_ifaces.sh {{ fabric_ip }}
  register: ifaces_changed
  changed_when: ifaces_changed.stdout != "false"

- name: Reboot Required
  become: yes
  command: /sbin/reboot
  when: ifaces_changed.stdout != "false"
