- name: Ensure MAAS Ansible Config Directory
  become: yes
  file:
    path=/etc/maas/ansible
    owner=maas
    group=maas
    state=directory

- name: Ensure Ansible Compute Config Files
  become: yes
  git:
    repo={{ provision.location }}
    dest=/tmp/ansible.maas
    clone=yes
    force=yes
    update=yes

- name: Ensure Ansible Roles Exist
  become: yes
  command: cp -rf /tmp/ansible.maas/{{ provision.role_path }} /etc/maas/ansible

- name: Ensure Ansible Roles Ownership
  become: yes
  file: dest=/etc/maas/ansible/{{ provision.role_path }} owner=maas group=maas recurse=yes

- name: Ensure Ansible Provisioning Script
  become: yes
  copy:
    dest=/etc/maas/ansible/{{ item }}
    src=files/{{ item }}
    owner=maas
    group=maas
    mode=0755
  with_items:
    - do-ansible
    - do-switch

- name: Ensure Provisioning Log Directory
  become: yes
  file:
    path=/etc/maas/ansible/logs
    state=directory
    owner=maas
    group=maas
    mode=0755

- name: Ensure Compute Node Playbook
  become: yes
  template:
    src=files/{{ item }}
    dest=/etc/maas/ansible/{{ item }}
    owner=maas
    group=maas
    mode=0644
  with_items:
    - compute-node.yml
    - switch-node.yml
