- name: Ensure MAAS Ansible Config Directory
  become: yes
  file:
    path=/etc/maas/ansible
    owner=maas
    group=maas
    state=directory

- name: Ensure Ansible Compute Config Files
  become: yes
  git:
    repo={{ provision.location }}
    dest=/tmp/ansible.maas
    clone=yes
    force=yes
    update=yes

- name: Ensure Ansible Roles Exist
  become: yes
  command: cp -rf /tmp/ansible.maas/{{ provision.role_path }} /etc/maas/ansible

- name: Ensure Ansible Roles Ownership
  become: yes
  file: dest=/etc/maas/ansible/{{ provision.role_path }} owner=maas group=maas recurse=yes

- name: Ensure Compute Node Playbook
  become: yes
  template:
    src=files/compute-node.yml.j2
    dest=/etc/maas/ansible/compute-node.yml
    owner=maas
    group=maas
    mode=0644
