- name: Ansible Repository
  become: yes
  apt_repository:
    repo: "{{ ansible_apt_repo | default('ppa:ansible/ansible') }}"

- name: Ensure Ansible
  become: yes
  apt:
    name=ansible=2.1.2.*
    state=present
