- name: Ansible Repository
  become: yes
  apt_repository:
    repo: "{{ ansible_apt_repo | default('ppa:ansible/ansible') }}"
  register: result
  until: result | success
  retries: 3
  delay: 10

- name: Ensure Ansible
  become: yes
  apt:
    name=ansible=2.2.*
    state=present
