---
galaxy_info:
  author: Ciena Blueplanet
  description: Docker Engine and Docker Compose
  company: Ciena Blueplanet
  license: Apache 2.0
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  galaxy_tags:
    - development
    - system
dependencies:
  - { role: local-ubuntu-repository, when: ubuntu_apt_repo is defined }
